# Generated by Django 2.1.15 on 2020-06-02 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pitrcade', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PollerbotData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=50)),
                ('value', models.CharField(max_length=100)),
            ],
        ),
    ]
