# Generated by Django 2.1.15 on 2020-06-11 05:05

import colorfield.fields
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('preferences', '0002_auto_20181220_0803'),
        ('pitrcade', '0002_pollerbotdata'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfigSettings',
            fields=[
                ('preferences_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='preferences.Preferences')),
                ('game_title', models.CharField(max_length=50)),
                ('max_score', models.IntegerField()),
                ('min_score', models.IntegerField()),
                ('scoreboard_refresh', models.IntegerField()),
                ('scoreboard_top_scores', models.IntegerField()),
                ('scorboard_title_color', colorfield.fields.ColorField(default='#FFFF00', max_length=18)),
                ('scorboard_header_color', colorfield.fields.ColorField(default='#FF0000', max_length=18)),
                ('scorboard_player_color', colorfield.fields.ColorField(default='#0000FF', max_length=18)),
                ('scorboard_next_player_reset', models.DateTimeField()),
                ('scorboard_player_reset_interval', models.DurationField()),
                ('normal_distribution_score', models.BooleanField(default=True)),
            ],
            bases=('preferences.preferences',),
            managers=[
                ('singleton', django.db.models.manager.Manager()),
            ],
        ),
    ]
