# Generated by Django 2.1.15 on 2020-06-11 05:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('preferences', '0002_auto_20181220_0803'),
        ('sites', '0002_alter_domain_unique'),
        ('pitrcade', '0003_configsettings'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ConfigSettings',
            new_name='ConfigSetting',
        ),
    ]
