# Generated by Django 2.1.15 on 2020-06-11 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pitrcade', '0004_auto_20200610_2221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configsetting',
            name='max_score',
            field=models.IntegerField(null=True),
        ),
    ]
