# Generated by Django 2.1.15 on 2020-06-11 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pitrcade', '0005_auto_20200610_2222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configsetting',
            name='max_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='configsetting',
            name='min_score',
            field=models.IntegerField(default=1000),
        ),
        migrations.AlterField(
            model_name='configsetting',
            name='scoreboard_refresh',
            field=models.IntegerField(default=15),
        ),
        migrations.AlterField(
            model_name='configsetting',
            name='scoreboard_top_scores',
            field=models.IntegerField(default=10),
        ),
    ]
