# Generated by Django 2.1.15 on 2020-06-11 05:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pitrcade', '0006_auto_20200610_2223'),
    ]

    operations = [
        migrations.RenameField(
            model_name='configsetting',
            old_name='scorboard_header_color',
            new_name='scoreboard_header_color',
        ),
        migrations.RenameField(
            model_name='configsetting',
            old_name='scorboard_player_color',
            new_name='scoreboard_player_color',
        ),
        migrations.RenameField(
            model_name='configsetting',
            old_name='scorboard_title_color',
            new_name='scoreboard_title_color',
        ),
        migrations.RemoveField(
            model_name='configsetting',
            name='scorboard_next_player_reset',
        ),
        migrations.RemoveField(
            model_name='configsetting',
            name='scorboard_player_reset_interval',
        ),
        migrations.AddField(
            model_name='configsetting',
            name='scoreboard_next_player_reset',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 17, 22, 26, 49, 504304)),
        ),
        migrations.AddField(
            model_name='configsetting',
            name='scoreboard_player_reset_interval',
            field=models.DurationField(default=datetime.timedelta(days=7)),
        ),
    ]
