# Generated by Django 2.1.15 on 2020-06-11 05:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pitrcade', '0009_auto_20200610_2232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configsetting',
            name='scoreboard_next_player_reset',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 17, 22, 47, 4, 798652)),
        ),
    ]
