# Generated by Django 2.1.15 on 2020-06-28 21:46

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('pitrcade', '0012_auto_20200610_2337'),
    ]

    operations = [
        migrations.CreateModel(
            name='PremadePoll',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True)),
                ('options', models.TextField()),
                ('multi', models.BooleanField(default=False)),
            ],
        ),
        migrations.AlterField(
            model_name='configsetting',
            name='scoreboard_next_player_reset',
            field=models.DateTimeField(default=datetime.datetime(2020, 7, 5, 21, 46, 9, 938397, tzinfo=utc)),
        ),
    ]
