# Generated by Django 2.1.15 on 2020-07-08 08:11

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('pitrcade', '0013_auto_20200628_1446'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameResultHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(auto_now_add=True)),
                ('score', models.IntegerField(default=0)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pitrcade.Player')),
            ],
        ),
        migrations.CreateModel(
            name='GameResultMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(default=-1, unique=True)),
                ('message', models.TextField(blank=True)),
                ('image_or_video_alert_url', models.TextField(blank=True)),
                ('sound_alert_url', models.TextField(blank=True)),
            ],
        ),
        migrations.DeleteModel(
            name='GameResult',
        ),
        migrations.AddField(
            model_name='configsetting',
            name='alert_duration',
            field=models.IntegerField(default=3),
        ),
        migrations.AddField(
            model_name='configsetting',
            name='streamlabs_access_token',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='configsetting',
            name='scoreboard_next_player_reset',
            field=models.DateTimeField(default=datetime.datetime(1970, 1, 1, 0, 0, tzinfo=utc)),
        ),
    ]
